/* eslint-disable */
/**
 * GENERATED by `npm run gen:types` from schemas/annotations.schema.json.
 * Do not edit by hand; regenerate after `room_gen schemas` changes the schema.
 */

export type Kind = 'wall_floor' | 'wall_ceiling' | 'wall_wall';
/**
 * @minItems 2
 */
export type Pixels = [[number, number], [number, number], ...[number, number][]];
export type By = 'auto' | 'human' | 'model' | 'fit';
export type Confidence = number;
export type Tool = string;
export type BoundaryLines = BoundaryLine[];
export type CameraHeightM = number | null;
export type Focal35Mm = number | null;
export type FocalMm = number | null;
export type Make = string | null;
export type Model = string | null;
export type Orientation = number | null;
export type FocalPx = number | null;
export type Axis = 'x' | 'y' | 'z';
/**
 * @minItems 2
 */
export type Lines = [
  [[number, number], [number, number]],
  [[number, number], [number, number]],
  ...[[number, number], [number, number]][]
];
export type ParallelPairs = ParallelPair[];
export type PrincipalPoint = [number, number] | null;
export type Kind1 = 'vertical';
export type Label = string;
export type Metres = number;
/**
 * @minItems 2
 * @maxItems 2
 */
export type Pixels1 = [[number, number], [number, number]];
export type VerticalLines = [[number, number], [number, number]][];
export type CeilingHeightM = number | null;
export type FloorCorners = [number, number][];
export type Image = string;
/**
 * @minItems 2
 * @maxItems 2
 */
export type ImageSize = [number, number];
export type Label1 = string;
export type Metres1 = number;
/**
 * @minItems 2
 * @maxItems 2
 */
export type Pixels2 = [[number, number], [number, number]];
export type KnownLengths = KnownLength[];
export type Notes = string[];
export type Archetype = string | null;
/**
 * @minItems 4
 * @maxItems 4
 */
export type Box = [number, number, number, number];
export type Id = string;
export type Label2 = string;
export type Mask = string | null;
export type MaterialsHint = string[];
export type Score = number | null;
export type Support = string;
export type Objects = ObjectAnnotation[];
export type Kind2 = 'door' | 'window' | 'opening';
export type Label3 = string;
/**
 * @minItems 4
 * @maxItems 4
 */
export type Quad = [[number, number], [number, number], [number, number], [number, number]];
export type WallHint = ('left' | 'right' | 'back' | 'front' | '0' | '1' | '2' | '3') | null;
export type Openings = OpeningAnnotation[];
export type SchemaVersion = 1;
export type World = string;

export interface Annotations {
  boundary_lines?: BoundaryLines;
  calibration?: CalibrationHints;
  ceiling_height_m?: CeilingHeightM;
  floor_corners?: FloorCorners;
  image: Image;
  image_size: ImageSize;
  known_lengths?: KnownLengths;
  notes?: Notes;
  objects?: Objects;
  openings?: Openings;
  provenance?: Provenance;
  schema_version?: SchemaVersion;
  world: World;
}
/**
 * A traced stretch of a room boundary: wall/floor, wall/ceiling, or a vertical wall/wall corner.
 *
 * Use when a corner's foot is hidden but the boundary itself is visible.
 *
 * This interface was referenced by `Annotations`'s JSON-Schema
 * via the `definition` "BoundaryLine".
 */
export interface BoundaryLine {
  kind: Kind;
  pixels: Pixels;
  provenance?: Provenance;
}
/**
 * This interface was referenced by `Annotations`'s JSON-Schema
 * via the `definition` "Provenance".
 */
export interface Provenance {
  by?: By;
  confidence?: Confidence;
  tool?: Tool;
}
/**
 * This interface was referenced by `Annotations`'s JSON-Schema
 * via the `definition` "CalibrationHints".
 */
export interface CalibrationHints {
  camera_height_m?: CameraHeightM;
  exif?: ExifInfo | null;
  focal_px?: FocalPx;
  parallel_pairs?: ParallelPairs;
  principal_point?: PrincipalPoint;
  reference?: Reference | null;
  vertical_lines?: VerticalLines;
}
/**
 * This interface was referenced by `Annotations`'s JSON-Schema
 * via the `definition` "ExifInfo".
 */
export interface ExifInfo {
  focal_35mm?: Focal35Mm;
  focal_mm?: FocalMm;
  make?: Make;
  model?: Model;
  orientation?: Orientation;
}
/**
 * This interface was referenced by `Annotations`'s JSON-Schema
 * via the `definition` "ParallelPair".
 */
export interface ParallelPair {
  axis: Axis;
  lines: Lines;
}
/**
 * A vertical segment standing on the floor (bottom pixel first) of known length.
 *
 * This interface was referenced by `Annotations`'s JSON-Schema
 * via the `definition` "Reference".
 */
export interface Reference {
  kind?: Kind1;
  label?: Label;
  metres: Metres;
  pixels: Pixels1;
}
/**
 * Two pixels on the floor plane a known distance apart.
 *
 * This interface was referenced by `Annotations`'s JSON-Schema
 * via the `definition` "KnownLength".
 */
export interface KnownLength {
  label?: Label1;
  metres: Metres1;
  pixels: Pixels2;
}
/**
 * This interface was referenced by `Annotations`'s JSON-Schema
 * via the `definition` "ObjectAnnotation".
 */
export interface ObjectAnnotation {
  archetype?: Archetype;
  box: Box;
  id: Id;
  label: Label2;
  mask?: Mask;
  materials_hint?: MaterialsHint;
  params?: Params;
  provenance?: Provenance;
  score?: Score;
  support?: Support;
}
export interface Params {
  [k: string]: unknown | undefined;
}
/**
 * This interface was referenced by `Annotations`'s JSON-Schema
 * via the `definition` "OpeningAnnotation".
 */
export interface OpeningAnnotation {
  kind: Kind2;
  label?: Label3;
  provenance?: Provenance;
  quad: Quad;
  wall_hint?: WallHint;
}
