// Generate src/types/annotations.ts from ../schemas/annotations.schema.json (CLAUDE.md §7).
// Usage: npm run gen:types            (writes the file)
//        npm run gen:types -- --check (exit 1 if the committed file is stale)
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(here, '../../schemas/annotations.schema.json');
const outPath = resolve(here, '../src/types/annotations.ts');

/**
 * Pydantic emits draft 2020-12 tuples (`prefixItems` + min/maxItems). json-schema-to-typescript
 * understands the older tuple form (`items: [...]`), so rewrite before compiling.
 */
export function toDraft7Tuples(node) {
  if (Array.isArray(node)) return node.map(toDraft7Tuples);
  if (!node || typeof node !== 'object') return node;
  const out = {};
  for (const [k, v] of Object.entries(node)) out[k] = toDraft7Tuples(v);
  if (Array.isArray(out.prefixItems)) {
    out.items = out.prefixItems;
    out.additionalItems = false;
    delete out.prefixItems;
  }
  return out;
}

export async function generate() {
  const schema = JSON.parse(await readFile(schemaPath, 'utf8'));
  const banner = [
    '/* eslint-disable */',
    '/**',
    ' * GENERATED by `npm run gen:types` from schemas/annotations.schema.json.',
    ' * Do not edit by hand; regenerate after `room_gen schemas` changes the schema.',
    ' */',
  ].join('\n');
  return compile(toDraft7Tuples(schema), 'Annotations', {
    bannerComment: banner,
    additionalProperties: false,
    unreachableDefinitions: true,
    strictIndexSignatures: true,
    style: { singleQuote: true, printWidth: 110 },
  });
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const ts = await generate();
  if (process.argv.includes('--check')) {
    const current = await readFile(outPath, 'utf8').catch(() => '');
    if (current !== ts) {
      console.error(`${outPath} is stale; run npm run gen:types`);
      process.exit(1);
    }
    console.log('types up to date');
  } else {
    await writeFile(outPath, ts);
    console.log(`wrote ${outPath}`);
  }
}
